### ISSUE TITLE
Filtering limit criteria

### ISSUE THREAD

**Issue by jasonlav** [nystudio107/craft-similar#15]
Is it possible to filter the similar results by a specific category?

For example, I have two categories associated with a blog post (fruit and vegetable). The results will be filtered by grape, but similar to carrot, broccoli, and onion.

I attempted to add a relationship to the limit criteria (`limitCriteria = craft.entries.relatedTo(grape).limit(2)`), but that simply yields no results.

**Comment by khalwat** [comment]
Not presently.
