### ISSUE TITLE
3.2 update - column craft_relations.sourceid does not exist

### ISSUE THREAD

**Issue by himynameisphil** [nystudio107/craft-similar#18]
Getting this error after updating to the latest Craft version (3.2.0).

`SQLSTATE[42703]: Undefined column: 7 ERROR: column craft_relations.sourceid does not exist`

**Comment by julienmarie** [comment]
Did you manage to fix it? I have the same error

**Comment by julienmarie** [comment]
It's been like 6 months ?

**Comment by khalwat** [comment]
if I had to guess, the issue would be here:

https://github.com/nystudio107/craft-similar/blob/v1/src/services/Similar.php#L102

Or here:

https://github.com/nystudio107/craft-similar/blob/v1/src/services/Similar.php#L136

@julienmarie PRs are welcome!

**Comment by khalwat** [comment]
This should be fixed in the dev-develop branch

You can try it now by setting your semver in your `composer.json` to look like this:
```json
    "nystudio107/craft-similar": "dev-develop as 1.1.0”,
```
Then do a `composer update`

Let me know how you go...

**Comment by khalwat** [comment]
Fixed in https://github.com/nystudio107/craft-similar/releases/tag/1.1.0
