### ISSUE TITLE
"Serialization of 'Closure' is not allowed" when trying to cache query from Similar

### ISSUE THREAD

**Issue by daltonrooney** [nystudio107/craft-similar#2]
Not sure if you saw this:
https://github.com/craftcms/cms/issues/2674

I am experiencing the same issue in the latest Craft 3. @aelvan did suggest that it should be fixed in Craft core, but since that may take a while I was wondering if you'd consider patching it in the plugin directly?

**Comment by khalwat** [comment]
Fixed in https://github.com/nystudio107/craft-similar/commit/3b87c79e60a8c964e5cd556813ae7cf3d818e85a
