### ISSUE TITLE
Undefined array key "1-92135"

### ISSUE THREAD

**Issue by lucosius** [nystudio107/craft-similar#30]
Hey,

Everything is working great but if my entry don't have any tags assigned I'm getting error. How can I make it work if there's no tags and nothing to show?

**Comment by khalwat** [comment]
This is the same as: https://github.com/nystudio107/craft-similar/issues/29

Fixed in https://github.com/nystudio107/craft-similar/commit/0d81f2f27cb698c469aefce68ad76379153ced0d

You can try it now by setting your semver in your `composer.json` to look like this:
```json
    "nystudio107/craft-similar": "dev-develop as 1.1.1”,
```
Then do a `composer update`
