### ISSUE TITLE
Error when using orderBy('RAND()') as criteria

### ISSUE THREAD

**Issue by ryanfoote** [nystudio107/craft-similar#32]
### Describe the bug
When `orderBy('RAND()')` is used as a criteria, Craft produces the following error:

```
Array to string conversion
```

### To reproduce
Apply `orderBy('RAND()')` to the criteria, like so:

```
{% set queryCriteria = craft.entries.limit(1).orderBy('RAND()') %}
{% set relatedContent = craft.similar.find({element: entry, context: entry.category, criteria: queryCriteria}) %}
```

### Expected behaviour
That the plugin would return a randomized set of entries.

### Screenshots
<img width="1909" alt="Screen Shot 2021-03-23 at 4 49 41 PM" src="https://user-images.githubusercontent.com/2237817/112233702-1aa36c00-8bf8-11eb-9428-57aad5638d7b.png">

### Versions
- Plugin version: 1.1.2
- Craft version: 3.6.11

**Comment by khalwat** [comment]
Fixed in https://github.com/nystudio107/craft-similar/releases/tag/1.1.3
