### ISSUE TITLE
Is there a way to limit results to one section and also related to categories and tags?

### ISSUE THREAD

**Issue by gbowne-quickbase** [nystudio107/craft-similar#42]
### Is your feature request related to a problem? Please describe.
We have some areas of our site where we want to link to all sorts of content, and some others where we just want similar items to a particular section. Is there a way to add that to the criteria? The readme didn't quite make that clear.

### Describe the solution you would like
If it's possible, add it to the readme, or suggest a workaround

### Describe alternatives you have considered
We tried getting more items back by upping the limit and then excluding them when looping through the results.

**Comment by khalwat** [comment]
I'm sorry, I don't fully understand what you're asking me?

**Comment by gbowne-quickbase** [comment]
Example 1: show me content on the site that is related to these industry categories. We've got that working well.
Example 2: show me content only in the Case Studies section/channel that is related to these industry categories.

**Comment by khalwat** [comment]
I'm thinking _probably_ you can do what you want with Similar, but you'd need to play around with the queries a bit to see if it'll work for you or not.

Not having it here to do the same, it's difficult for me to give you a firm answer.
