### ISSUE TITLE
element parameter is redundant in certain scenarios

### ISSUE THREAD

**Issue by joshuabaker** [nystudio107/craft-similar#9]
I have a scenario where providing a the `element` is redundant. I just want to get the best matches for the provided `context`.

The only requirement for this, at present, is to determine the element type and remove the element from the result set. The former can be achieved looking at the `criteria` and the latter isn’t always required.

Leaving here for myself, in case I find time to put together a PR. Let me know your thoughts.

**Comment by khalwat** [comment]
Can you give me a code example of what you mean?

**Comment by joshuabaker** [comment]
Essentially, what I’m talking about is searching.

Below is an example scenario where we’re looking for people that have worked at a specific company and we want to order by matches with some skills.

```twig
{% set element = entry %}{# The homepage, perhaps (i.e. redundant for this query) #}

{% set context = craft.categories({
  relatedTo: skillIds,
}) %}

{% set criteria = craft.entries({
  section: 'people',
  relatedTo: companyIds,
  limit: 3,
}) %}

{% set results = craft.similar.find({
  element: element,
  context: context,
  criteria: criteria,
}) %}
```

The above works, however, when we’re on a page where there’s no element object we have to add a query to get a random element.

**Comment by khalwat** [comment]
So the `element` is required because that's what it uses to create the Element Query. I suppose it could fall back to a default generic `ElementQuery` or `EntryQuery` or such, but I'm wondering if having to be explicit/consistent about it makes sense regardless?

**Comment by joshuabaker** [comment]
Is the `criteria` element type not sufficient for this though?

**Comment by khalwat** [comment]
I think it's probably best to keep the API consistent in the end.

**Comment by joshuabaker** [comment]
![giphy](https://user-images.githubusercontent.com/160484/109491788-f08bdd80-7a81-11eb-91bc-04d31fdaf7d3.gif)
